baseURL = "https://d2d06xlq6t9xmp.cloudfront.net/"
theme = "github.com/mrmierzejewski/hugo-theme-console"
title = "trinity-klein"
description = "CIS Grad | Developer | Terminal Portfolio"
languageCode = "en-us"
relativeURLs = false 
canonifyURLs = true 

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

   [[params.navlinks]]
   name = "blogs/"
   url = "/posts.html"

  [[params.navlinks]]
  name = "projects/"
  url = "/projects.html"

  [[params.navlinks]]
  name = "resume/"
  url = "/resume.html"
  
  [[params.navlinks]]
  name = "contact/"
  url = "/ping.html"

[deployment]
  [[deployment.targets]]
    name = "aws"
    URL = "s3://tlklein-portfolio-v2?region=us-east-2"
    cloudFrontDistributionID = "E3CEI4S8QN6ZBW"

  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg|png|jpg|jpeg|gif|woff2?)$"
    cacheControl = "max-age=31536000, no-transform, public"
