name: Build and Deploy Static Site

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  SOURCE_DIR: ./public
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION }}
  BASE_URL: "https://d2d06xlq6t9xmp.cloudfront.net/"
  SITE_TITLE: "Trinity Klein"

jobs:
  # JOB 1 - BUILD JOB
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
      
      - name: Override config.toml values
        run: |
          sed -i 's|^baseURL = .*|baseURL = "${{ env.BASE_URL }}"|' config.toml
          sed -i 's|^title = .*|title = "${{ env.SITE_TITLE }}"|' config.toml

      - name: Build Hugo site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public/

  # JOB 2️ - DEPLOY JOB
  deploy-site:
    needs: build-site
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./public

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete old index.html
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }}/index.html || true

      - name: Sync site to S3
        run: |
          aws s3 sync ./public s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ env.AWS_REGION }}

  # JOB 3️ - SMOKETEST JOB
  smoketests:
    needs: deploy-site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for tests)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/ 