name: "Code Validation Checks" 

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

env:
  BASE_URL: https://www.trinityklein.dev/

jobs:
  #################################################################
  # HTML-validate, markdownlint-cli, and Linkinator Checks
  #################################################################
  build-html:
    name: build-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "README.md" # Will run through node modules if using the wildcard

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'

      - name: Build Hugo site
        run: hugo build --baseURL=${{ env.BASE_URL }}
        
      - name: Install HTML-Validate and Linkinator
        run: |
          npm install -g html-validate linkinator

      - name: Run html-validate
        run: html-validate "layouts/**/*.html" "static/**/*.html"

      - name: Run Linkinator (skip external blocked links)
        run: |
          linkinator ./public --skip "livereload,linkedin.com,facebook.com,twitter.com,instagram.com"

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./public

  #################################################################
  # Playwright tests (run against local server built from PR)
  #################################################################
  playwright:
    name: playwright-tests
    runs-on: ubuntu-latest
    needs: build-html
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
      
      - name: Install dependencies
        run: npm install --save-dev wait-on

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Serve site in background
        run:  hugo server -D --bind 0.0.0.0 --baseURL http://localhost:1313 &

      - name: Wait for server
        run: npx wait-on http://localhost:1313

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:1313
        run: npx playwright test tests/

      - name: Stop server
        run: pkill -f "hugo server"
        if: always()