name: Copy website to S3 and invalidate CloudFront Distribution

on:
  push:
    branches:
      - main

jobs:
  # JOB 1 - Copy code from /public folder and put it into the s3 bucket
  copy-website-to-s3-and-invalidate-cloudfront:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0' 

      - name: Build Hugo site
        run: hugo

      - name: Upload to S3 (only from public/)
        run: |
          aws s3 sync ./public s3://$AWS_S3_BUCKET \
            --delete \
            --region $AWS_REGION
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'us-east-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Job 2 - Create a CloudFront invalidation to index.html
  invalidate-cloudfront-distribution:
    needs: copy-website-to-s3-and-invalidate-cloudfront
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/index.html" # /* makes an invalidation to all files (just in case)
          AWS_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  # Job 3 - Run playwright smoke tests
  run-playwright-tests:
    name: Run Playwright Tests
    needs: invalidate-cloudfront-distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fix Playwright executable permission
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test tests/