name: "Site Validation"

on:
  push:
    branches:
      - main
      - dev
      - feature
  pull_request:
    branches:
      - main
      - dev
      - feature

permissions:
  contents: read
  security-events: write

jobs:
  site-validate:
    runs-on: ubuntu-latest
    ################################################################## 
    # Site validation using html-validate, linkinator,  & markdownlint
    ##################################################################
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -g markdownlint-cli linkinator
      - run: markdownlint "README.md"
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
      - run: hugo --baseURL="${{ env.BASE_URL }}"
     # - run: html-validate "dist/index.html"
      - run: linkinator ./dist --skip "livereload,linkedin.com,facebook.com,twitter.com,instagram.com"
